version: '2'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: ${DOCKER_HOST_IP}
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "test:1:1"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  kafkacat:
    image: confluentinc/cp-kafkacat
    ports:
      - "29092:29092"
  sdw_depositor:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DOCKER_HOST_IP: ${DOCKER_HOST_IP}
      SDW_EMAIL_LIST: ${SDW_EMAIL_LIST}
      SDW_EMAIL_FROM: ${SDW_EMAIL_FROM}
      SDW_API_KEY: ${SDW_API_KEY}
      SDW_DESTINATION_URL: ${SDW_DESTINATION_URL}
      SPRING_MAIL_HOST: ${SPRING_MAIL_HOST}
      SPRING_MAIL_PORT: ${SPRING_MAIL_PORT}
      SDW_SUBSCRIPTION_TOPIC: ${SDW_SUBSCRIPTION_TOPIC}
    logging:
      options:
        max-size: "10m"
        max-file: "5"